<?php

/**
 * السجل المركزي لصلاحيات نظام Wesal
 *
 * Actions: عرض (قراءة) | إنشاء | تعديل | حذف | تنفيذ
 * عند إضافة زر أو قسم فرعي: أضف الصلاحية المناسبة ضمن القسم — ستظهر تلقائياً في مصفوفة الصلاحيات
 */
return [
    'guard' => 'web',

    /** تسميات الأدوار بالعربي (للأعمدة في مصفوفة الصلاحيات) */
    'roles_label_ar' => [
        'SuperAdmin' => 'المدير الأعلى',
        'Admin' => 'مدير النظام',
        'FinanceViewer' => 'مشاهد المالية',
        'FinanceAccountant' => 'محاسب',
        'FinanceAdmin' => 'مدير مالي',
        'FinanceSuperAdmin' => 'مدير مالي أول',
        'Donor' => 'جهة مانحة (متابعة المشاريع)',
    ],

    /** أدوار محمية */
    'protected_roles' => ['SuperAdmin'],

    /**
     * الأقسام والصلاحيات — تتحدث تلقائياً عند إضافة عناصر
     * كل قسم: عرض (قراءة) + إنشاء + تعديل + حذف + تنفيذ (حسب الحاجة)
     */
    'groups' => [
        [
            'label' => 'الرئيسية والأقسام الرئيسية',
            'permissions' => [
                'wesal.home' => 'عرض الرئيسية',
                'wesal.e-office' => 'عرض المكتب الإلكتروني',
                'wesal.finance' => 'عرض المالية',
                'wesal.hr' => 'عرض الموارد البشرية',
                'wesal.beneficiaries' => 'عرض المستفيدين',
                'wesal.programs-projects' => 'عرض البرامج والمشاريع',
                'wesal.meetings' => 'عرض الاجتماعات',
                'wesal.communications' => 'عرض الاتصالات الإدارية',
                'wesal.administrative-requests' => 'عرض الطلبات الإدارية (طلب إجازة / عام / مالي / حضور وانصراف)',
                'wesal.users' => 'إدارة المستخدمين والصلاحيات',
                'wesal.system-settings' => 'إعدادات النظام',
                'wesal.website' => 'إدارة الموقع الإلكتروني',
            ],
        ],
        [
            'label' => 'المكتب الإلكتروني',
            'permissions' => [
                'e-office.mail.view' => 'قراءة البريد',
                'e-office.mail.send' => 'إرسال بريد',
                'e-office.tasks.view' => 'عرض المهام',
                'e-office.tasks.create' => 'إنشاء مهمة',
                'e-office.tasks.edit' => 'تعديل مهمة',
                'e-office.tasks.delete' => 'حذف مهمة',
                'e-office.tasks.close' => 'إغلاق مهمة',
            ],
        ],
        [
            'label' => 'الصلاحيات المالية',
            'permissions' => [
                'finance.view' => 'عرض المالية',
                'finance.chart_accounts.view' => 'عرض دليل الحسابات',
                'finance.chart_accounts.create' => 'إنشاء حساب',
                'finance.chart_accounts.edit' => 'تعديل حساب',
                'finance.chart_accounts.delete' => 'حذف حساب',
                'finance.journal.view' => 'عرض القيود',
                'finance.journal.create' => 'إنشاء قيد',
                'finance.journal.edit' => 'تعديل قيد',
                'finance.payment_requests.view' => 'عرض طلبات الصرف',
                'finance.payment_requests.create' => 'إنشاء طلب صرف',
                'finance.payment_requests.approve' => 'اعتماد طلب صرف',
                'finance.accountant' => 'تنفيذ عمليات المحاسب',
                'finance.admin' => 'إدارة المالية',
                'finance.super_admin' => 'مدير مالي أول',
            ],
        ],
        [
            'label' => 'الموارد البشرية',
            'permissions' => [
                'hr.employees.view' => 'عرض الموظفين',
                'hr.employees.create' => 'إضافة موظف',
                'hr.employees.edit' => 'تعديل موظف',
                'hr.employees.delete' => 'حذف موظف',
                'hr.departments.view' => 'عرض الأقسام',
                'hr.departments.create' => 'إضافة قسم',
                'hr.departments.edit' => 'تعديل قسم',
                'hr.departments.delete' => 'حذف قسم',
                'hr.attendance.view' => 'عرض الحضور',
                'hr.attendance.record' => 'تسجيل الحضور',
                'hr.leave.view' => 'عرض الإجازات',
                'hr.leave.request' => 'طلب إجازة',
                'hr.leave.approve' => 'اعتماد إجازة',
                'hr.leave_types.view' => 'عرض أنواع الإجازات',
                'hr.leave_types.create' => 'إضافة نوع إجازة',
                'hr.leave_types.edit' => 'تعديل نوع إجازة',
                'hr.leave_types.delete' => 'حذف نوع إجازة',
                'hr.payroll.view' => 'عرض الرواتب',
                'hr.payroll.run' => 'تنفيذ مسير الرواتب',
                'hr.advances.view' => 'عرض السلف',
                'hr.advances.create' => 'إضافة سلفة',
                'hr.advances.approve' => 'اعتماد سلفة',
                'hr.allowance_deduction.view' => 'عرض المخصصات والخصومات',
                'hr.allowance_deduction.create' => 'إضافة مخصص/خصم',
                'hr.allowance_deduction.delete' => 'حذف مخصص/خصم',
                'hr.contracts.view' => 'عرض العقود',
                'hr.contracts.create' => 'إضافة عقد',
                'hr.contracts.delete' => 'حذف عقد',
                'hr.letters.view' => 'عرض الخطابات',
                'hr.letters.create' => 'إضافة خطاب',
                'hr.letters.delete' => 'حذف خطاب',
                'hr.decisions.view' => 'عرض القرارات',
                'hr.decisions.create' => 'إضافة قرار',
                'hr.decisions.delete' => 'حذف قرار',
                'hr.shifts.view' => 'عرض الورديات',
                'hr.shifts.create' => 'إضافة وردية',
                'hr.shifts.edit' => 'تعديل وردية',
                'hr.shifts.delete' => 'حذف وردية',
                'hr.request_settings.view' => 'عرض إعدادات الطلبات',
                'hr.request_settings.edit' => 'تعديل تسلسل الموافقات',
            ],
        ],
        [
            'label' => 'المستفيدين',
            'permissions' => [
                'beneficiaries.view' => 'عرض المستفيدين',
                'beneficiaries.create' => 'إضافة مستفيد',
                'beneficiaries.edit' => 'تعديل مستفيد',
                'beneficiaries.delete' => 'حذف مستفيد',
                'beneficiaries.archive' => 'أرشفة مستفيد',
                'beneficiaries.requests.view' => 'عرض الطلبات',
                'beneficiaries.requests.approve' => 'اعتماد طلب',
                'beneficiaries.requests.reject' => 'رفض طلب',
                'beneficiaries.registration.view' => 'عرض طلبات التسجيل',
                'beneficiaries.registration.approve' => 'اعتماد طلب تسجيل',
                'beneficiaries.services.view' => 'عرض الخدمات',
                'beneficiaries.services.create' => 'إضافة خدمة',
            ],
        ],
        [
            'label' => 'البرامج والمشاريع',
            'permissions' => [
                'programs-projects.view' => 'عرض المشاريع',
                'programs-projects.projects.view' => 'عرض قائمة المشاريع',
                'programs-projects.projects.create' => 'إضافة مشروع',
                'programs-projects.projects.edit' => 'تعديل مشروع',
                'programs-projects.projects.delete' => 'حذف مشروع',
                'programs-projects.donors.view' => 'عرض الجهات المانحة',
                'programs-projects.donors.create' => 'إضافة جهة مانحة',
                'programs-projects.donors.edit' => 'تعديل جهة مانحة',
                'programs-projects.stages.view' => 'عرض المراحل',
                'programs-projects.stages.create' => 'إضافة مرحلة',
                'programs-projects.stages.edit' => 'تعديل مرحلة',
                'programs-projects.expenses.view' => 'عرض المصروفات',
                'programs-projects.expenses.create' => 'إضافة مصروف',
                'programs-projects.documents.view' => 'عرض المستندات',
                'programs-projects.documents.create' => 'إضافة مستند',
                'programs-projects.documents.delete' => 'حذف مستند',
                'donor.view_projects' => 'جهة مانحة: عرض مشاريعها فقط (مراحل وتحديثات)',
            ],
        ],
        [
            'label' => 'الاجتماعات',
            'permissions' => [
                'meetings.board.view' => 'عرض اجتماعات المجلس',
                'meetings.board.create' => 'إنشاء اجتماع مجلس',
                'meetings.board.edit' => 'تعديل اجتماع مجلس',
                'meetings.board.delete' => 'حذف اجتماع مجلس',
                'meetings.staff.view' => 'عرض اجتماعات الموظفين',
                'meetings.staff.create' => 'إنشاء اجتماع موظفين',
                'meetings.staff.edit' => 'تعديل اجتماع موظفين',
                'meetings.decisions.view' => 'عرض قرارات المجلس',
                'meetings.decisions.create' => 'إنشاء قرار',
                'meetings.decisions.edit' => 'تعديل قرار',
                'meetings.members.view' => 'عرض أعضاء المجلس',
                'meetings.members.create' => 'إضافة عضو مجلس',
                'meetings.members.edit' => 'تعديل عضو مجلس',
                'meetings.types.view' => 'عرض أنواع الاجتماعات',
                'meetings.types.create' => 'إضافة نوع اجتماع',
                'meetings.types.edit' => 'تعديل نوع اجتماع',
            ],
        ],
        [
            'label' => 'المستخدمين والأدوار',
            'permissions' => [
                'users.view' => 'عرض المستخدمين',
                'users.create' => 'إضافة مستخدم',
                'users.edit' => 'تعديل مستخدم',
                'users.delete' => 'حذف مستخدم',
                'users.roles.assign' => 'تعيين الأدوار',
                'roles.view' => 'عرض الأدوار',
                'roles.create' => 'إنشاء دور',
                'roles.edit' => 'تعديل صلاحيات الدور',
                'roles.delete' => 'حذف دور',
            ],
        ],
    ],
];
